---
  - name: ensure the system can use the HTTPS transport for API
      stat:
        path: /usr/lib/apt/methods/https
      register: apt_https_transport
  
  - name: install API HTTPS transport.
    apt:
      name: "apt-transport-https"
      state: present
      update_cache: yes
    when: not apt_https_transport.stat.exists
  
  - name: install basic required packages
    package:
      name: ['vim', 'aptitude', 'bash-completion', 'tree', 'htop', 'wget', 'unzip', 'curl', 'git']
      state: present
      update_cache: yes

  - name: install defualt Java 
     apt:
      name: defautl-jdk
      state: present
  
  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /usr/share/tomcat
      createhome: no
      system: yes
  
  - name: download tomcat
    get_url:
      url: "{{ tomcat_archive_url }}"
      dest: "{{ tomcat_archive_dest }}"

  - name: create a tomcat directory
    file:
      path: /usr/share/tomcat
      state: directory
      owner: tomcat
      group: tomcat

  - name: extract tomcat archive
    unarchive:
      src: "{{ tomcat_archive_dest }}"
      dest: /usr/share/tomcat
      owner: tomcat
      group: tomcat
      remote_src: yes
      extra_opts: "--strip-components=1"
      creates: /usr/share/tomcat/bin

  - name: copy tomcat service file
    template:
      src: templates/tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
    when: ansible_service_mgr == "systemd"
    
  - name: start and enable tomcat
    service:
      daemon_reload: yes
      name: tomcat
      state: started
      enabled: yes
    when: ansible_service_mgr == "systemd"


  - name: set ui access credentials
    tempalate:
      src: tomcat-users.xml.j2
      dest: /usr/share/tomcat/conf/tomcat-usrers.xml
    notify: restart tomcat
  
  - name: allow access to manager and host manager apps from any ip
    template:
      src: context.xml.j2
      dest: "{{ item }}"
    with_items:
      - /usr/share/tomcat/webapps/host-manager/META-INF/context.xml
      - /usr/share/tomcat/webapps/manager/META-INF/context.xml
    notify: restart tomcat
  
  - 
